### ISSUE TITLE
Unable to set Datasource property 

### ISSUE THREAD

**Issue by jried31** [ninjaprox/NVBnbCollectionView#4]
Hi, I'm unable to assign the datasource property of your collectionview. So numberofBNBrows...() isn't being called. I tried to create my own accessors like

@property (nonatomic) id<NVBnbCollectionViewDataSource>bnbDataSource;

No solution worked. Any fix? I'm creating my own instance of the collectionview programatically.

Jerrid

**Comment by ninjaprox** [comment]
@jried31: Could you provide some code snippets? It helps to figure out the issue.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
