### ISSUE TITLE
I want on click image

### ISSUE THREAD

**Issue by arno608rw** [ninjaprox/NVBnbCollectionView#5]
I want on click image

**Comment by ninjaprox** [comment]
I guess you meant on click of cell. If so, have you tried `- collectionView:didSelectItemAtIndexPath:`?

**Comment by arno608rw** [comment]
Yes

**Comment by ninjaprox** [comment]
Doesn't it meet your requirement? You could add gesture recognition to handle on touch image.

**Comment by ninjaprox** [comment]
Close this, reopen if need be.
