### ISSUE TITLE
How can i remove header?

### ISSUE THREAD

**Issue by bintu1234** [ninjaprox/NVBnbCollectionView#7]
How can i remove the header in collectionview, and can we able to change the size of the cell?

**Comment by ninjaprox** [comment]
@bintu1234: To remove header, simply leave `headerSize` zero. And sure, you can change cell size, please look at [Size](https://github.com/ninjaprox/NVBnbCollectionView#size).

**Comment by bintu1234** [comment]
@ninjaprox  Sorry But where i can set the headersize ?

**Comment by ninjaprox** [comment]
@bintu1234: It's member of `NVBnbCollectionViewLayout`, you can also find detail [here](http://cocoadocs.org/docsets/NVBnbCollectionView/1.0.0/Classes/NVBnbCollectionViewLayout.html#//api/name/headerSize).
